version: "3.7"

volumes:
  application-db:
    external: false
  cms-db-data:
    external: false
  processor-db:
    external: false

services:
  gateway:
    image: hasadna/open-pension-gateway:latest
    build:
      context: ./gateway
      cache_from:
        - hasadna/open-pension-gateway:latest

  application:
    image: hasadna/open-pension-application:latest
    build:
      context: ./application
      cache_from:
        - hasadna/open-pension-application:latest
    depends_on:
      - application_db
    env_file:
      - ./application/.env

  application_db:
    image: postgres:12.1-alpine
    volumes:
      - application-db:/var/lib/postgresql/db-data

  client:
    image: hasadna/open-pension-client:latest
    build:
      context: ./client
      cache_from:
        - hasadna/open-pension-client:latest
    ports:
      - "80:80"
    environment:
      - SERVICE_PORTS=80
    depends_on:
      - gateway

  processor:
    image: hasadna/open-pension-processor:latest
    build:
      context: ./processor
      cache_from:
        - hasadna/open-pension-processor:latest
    environment:
      - MONGO_URL=mongodb://processor_db:27017/
      - PYTHONUNBUFFERED=true
    depends_on:
      - processor_db

  processor_db:
    image: mongo
    volumes:
      - processor-db:/data/db

  cms:
    image: hasadna/open-pension-cms:latest
    depends_on:
      - cms_db
    build:
      context: ./cms
      cache_from:
        - hasadna/open-pension-cms:latest

  cms_db:
    image: mysql:5.7
    volumes:
      - cms-db-data:/var/lib/mysql

  kafka:
    image: hasadna/open-pension-kafka:latest
    build:
      context: ./kafka
      cache_from:
        - hasadna/open-pension-kafka:latest
    environment:
      - BROKER_ID=1
    depends_on:
      - zookeeper

  kafka2:
    image: hasadna/open-pension-kafka:latest
    environment:
      - BROKER_ID=2
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5
